export const GET_ORDER_ID_REQUEST = 'GET_ORDER_ID_REQUEST';
export const GET_ORDER_ID_FAILED = 'GET_ORDER_ID_FAILED';
export const GET_ORDER_ID_SUCCESS = 'GET_ORDER_ID_SUCCESS';
export const CLEAR_ORDER_ID = 'CLEAR_ORDER_ID';